services:
  - type: web
    name: ai-resume-backend
    runtime: node
    rootDir: backend
    plan: free

    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start

    autoDeploy: true
