import PDFDocument from 'pdfkit';
import { Response } from 'express';

export const generatePDFReport = (res: Response, title: string, data: Record<string, unknown>): void => {
  const doc = new PDFDocument({ margin: 50 });
  
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${title.replace(/\s+/g, '-')}.pdf"`);
  
  doc.pipe(res);
  
  doc.fontSize(24).fillColor('#6366f1').text('ResumeIQ AI', { align: 'center' });
  doc.moveDown();
  doc.fontSize(18).fillColor('#000').text(title, { align: 'center' });
  doc.moveDown(2);
  
  doc.fontSize(12).fillColor('#333');
  
  const writeSection = (heading: string, content: unknown) => {
    doc.fontSize(14).fillColor('#6366f1').text(heading);
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#333');
    
    if (Array.isArray(content)) {
      content.forEach((item) => {
        doc.text(`• ${typeof item === 'object' ? JSON.stringify(item) : item}`);
      });
    } else if (typeof content === 'object' && content !== null) {
      Object.entries(content).forEach(([key, value]) => {
        doc.text(`${key}: ${value}`);
      });
    } else {
      doc.text(String(content));
    }
    doc.moveDown();
  };

  Object.entries(data).forEach(([key, value]) => {
    writeSection(key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase()), value);
  });

  doc.fontSize(10).fillColor('#999').text(
    `Generated by ResumeIQ AI - ${new Date().toLocaleDateString()}`,
    50,
    doc.page.height - 50,
    { align: 'center' }
  );

  doc.end();
};
